# Generated by Django 2.2.4 on 2019-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191026_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_f', null=True, upload_to='', width_field='width_f'),
        ),
    ]
