# Generated by Django 2.2.4 on 2019-10-26 13:42

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191026_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_f', null=True, upload_to=post.models.upload_location, width_field='width_f'),
        ),
    ]
